name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # Enable Git LFS checkout

      - name: Install Git LFS and push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git lfs track "*.pth" "*.h5" "*.keras" "*.pt"
          git push --force https://gowtham-0010:$HF_TOKEN@huggingface.co/spaces/gowtham-0010/Digit-Recognizer-CNN main
